// Auto-generated configuration directly sourced from data/royal-rasoi.json
export interface MenuItem {
  id: string;
  name: string;
  hindiName?: string;
  category: "Starters" | "Main Course" | "Biryani & Rice" | "Tandoori & Breads" | "Chinese & Snacks" | "Beverages";
  isVeg: boolean;
  price: number;
  description: string;
  spicyLevel: 1 | 2 | 3;
  isChefSpecial?: boolean;
  image: string;
  serves: string;
}

export interface Review {
  id: string;
  guestName: string;
  city: string;
  rating: number;
  comment: string;
  date: string;
  dishLoved: string;
  images?: string[];
}

export interface CustomerPhoto {
  url: string;
  title: string;
  author: string;
}

export const royalConfig = {
  restaurant: {
    name: "The Royal Rasoi",
    tagline: "Flavors for Royalty • Authentic North Indian & Chinese Cuisine",
    subtitle: "Fine Dining Restaurant in Sadikpur, Patna",
    establishedYear: "2018",
    rating: "4.7",
    totalReviews: "520+ Google Reviews",
    guestsServed: "3,850+ Gourmands Served",
    priceForTwo: "INR 500",
    address: "City Court, near Smart Point, Sadikpur, Patna, Bihar 800007",
    phone: "099056 04856",
    googleMapsUrl: "https://www.google.com/maps/place/The+Royal+Rasoi/@25.6063597,75.4530912,6z/data=!4m10!1m2!2m1!1sroyal+rasoi!3m6!1s0x39ed5f7b28401aff:0x48badbd4cd527fe2!8m2!3d25.6063597!4d85.2089506!15sCgtyb3lhbCByYXNvaZIBEWluZGlhbl9yZXN0YXVyYW504AEA!16s%2Fg%2F11yjlngqmv?hl=en-IN&entry=ttu",
    swiggyUrl: "https://www.swiggy.com/restaurants/1309308/dineout",
    hours: {
      lunch: "11:00 AM – 04:00 PM",
      dinner: "04:00 PM – 10:30 PM",
      days: "Open All 7 Days"
    },
    amenities: ["Parking", "Air-Conditioned", "Cozy Celebrations (10-12)", "Takeaway & Delivery", "SwiggyPay accepted"],
    chef: {
      name: "The Royal Kitchen Team",
      title: "Master Culinary Khansamas",
      experience: "Authentic Mughlai & Awadhi Heritage",
      bio: "Mastering the culinary art of slow-cooked Dum Handis, charcoal tandoori grills, and hand-ground spices to deliver authentic flavors at City Court, Sadikpur, Patna."
    }
  },

  menuPages: [
  "/data/menu/menu-page-1.JPG",
  "/data/menu/menu-page-2.JPG",
  "/data/menu/menu-page-3.JPG",
  "/data/menu/menu-page-4.JPG",
  "/data/menu/menu-page-5.JPG",
  "/data/menu/menu-page-6.JPG",
  "/data/menu/menu-page-7.JPG"
],

  customerPhotos: [
  {
    "url": "/data/reviews/review-image-1.jpg",
    "title": "Special Tandoori Feast",
    "author": "Amarjeet Yadav"
  },
  {
    "url": "/data/reviews/review-image-2.jpg",
    "title": "Delicious Spread",
    "author": "Amarjeet Yadav"
  },
  {
    "url": "/data/reviews/review-image-3.jpg",
    "title": "Restaurant Interior & Seating",
    "author": "Rameez Ahmad"
  },
  {
    "url": "/data/reviews/review-image-4.jpg",
    "title": "Comfortable Dining Area",
    "author": "Rameez Ahmad"
  },
  {
    "url": "/data/reviews/review-image-6.jpg",
    "title": "Popular Dishes Served",
    "author": "Dipanshu Sharma"
  },
  {
    "url": "/data/reviews/review-image-7.jpg",
    "title": "Cozy Palace Ambience",
    "author": "Tripti Chawla"
  },
  {
    "url": "/data/reviews/review-image-8.jpg",
    "title": "Evening Dining Setup",
    "author": "Tripti Chawla"
  },
  {
    "url": "/data/reviews/review-image-9.jpg",
    "title": "Freshly Grilled Tandoori",
    "author": "Customer Photo"
  },
  {
    "url": "/data/reviews/review-image-10.jpg",
    "title": "Signature Dish Platter",
    "author": "Customer Photo"
  }
] as CustomerPhoto[],

  reviews: [
  {
    "id": "r-1",
    "guestName": "Amarjeet_Yadav",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Food is tasty, delicious and pocket friendly. You should visit once.",
    "date": "Edited 4 months ago",
    "dishLoved": "Chicken Tikka & Biryani",
    "images": [
      "/data/reviews/review-image-1.jpg",
      "/data/reviews/review-image-2.jpg"
    ]
  },
  {
    "id": "r-2",
    "guestName": "Gourav kumar",
    "city": "Sadikpur, Patna",
    "rating": 1,
    "comment": "Reported a serious quality issue with Chicken Lollipop.",
    "date": "a month ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  },
  {
    "id": "r-3",
    "guestName": "Rameez Ahmad",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Good people, good service, good place, good view and comfortable seating.",
    "date": "a year ago",
    "dishLoved": "Special Tandoori & Kebabs",
    "images": [
      "/data/reviews/review-image-3.jpg",
      "/data/reviews/review-image-4.jpg"
    ]
  },
  {
    "id": "r-4",
    "guestName": "Ravi Gupta",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Delicious food and very professional staff. Must try food.",
    "date": "6 months ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  },
  {
    "id": "r-5",
    "guestName": "Dipanshu Sharma",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Best restaurant.",
    "date": "6 months ago",
    "dishLoved": "North Indian Specialties",
    "images": [
      "/data/reviews/review-image-6.jpg"
    ]
  },
  {
    "id": "r-6",
    "guestName": "Rabia",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Wonderful experience, delicious food, cozy atmosphere and warm service.",
    "date": "a year ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  },
  {
    "id": "r-7",
    "guestName": "AK J",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "The food they serve is very awesome and delicious.",
    "date": "2 months ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  },
  {
    "id": "r-8",
    "guestName": "Anubhavi",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Cafe was good and affordable, with good employee behaviour.",
    "date": "7 months ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  },
  {
    "id": "r-9",
    "guestName": "Tripti Chawla",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Awesome ambience. Food was too good.",
    "date": "a year ago",
    "dishLoved": "Tandoori Starters & Ambience",
    "images": [
      "/data/reviews/review-image-7.jpg",
      "/data/reviews/review-image-8.jpg"
    ]
  },
  {
    "id": "r-10",
    "guestName": "Abhi decoration Agency",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Very good and very tasty food.",
    "date": "9 months ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  }
] as Review[],

  menu: [
  {
    "id": "m-1",
    "name": "Chicken Chilli",
    "category": "Starters",
    "isVeg": false,
    "price": 170,
    "description": "Crispy fried chicken chunks tossed in fiery green chillies, garlic, soy sauce, and crunchy bell peppers.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-chilli.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-2",
    "name": "Chicken Boneless Chilli",
    "category": "Starters",
    "isVeg": false,
    "price": 179,
    "description": "Tender boneless chicken cubes wok-tossed in spicy Indo-Chinese dark soya glaze with spring onions.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-3",
    "name": "Chicken Manchurian",
    "category": "Starters",
    "isVeg": false,
    "price": 235,
    "description": "Juicy chicken meatballs glazed in savory, tangy ginger-coriander Manchurian gravy.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-manchurian.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-4",
    "name": "Chicken 65",
    "category": "Starters",
    "isVeg": false,
    "price": 240,
    "description": "Crispy, spicy South-Indian style boneless chicken tempered with mustard seeds, curry leaves, and red chillies.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-65.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-5",
    "name": "Chicken Schezwan",
    "category": "Starters",
    "isVeg": false,
    "price": 240,
    "description": "Fiery wok-tossed chicken chunks simmered in authentic Sichuan pepper and roasted red chilli paste.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-6",
    "name": "Chicken Tikka",
    "category": "Starters",
    "isVeg": false,
    "price": 300,
    "description": "Boneless chicken marinated in hung curd and hand-pounded mustard spices, flame-roasted in a clay tandoor.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-7",
    "name": "Chicken Seekh Kebab",
    "category": "Starters",
    "isVeg": false,
    "price": 329,
    "description": "Minced royal chicken blended with Lucknowi aromatics, skewered and charcoal-grilled to melt-in-mouth perfection.",
    "spicyLevel": 2,
    "isChefSpecial": true,
    "image": "/data/dishes/chicken-seekh-kebab.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-8",
    "name": "Chicken Lollipop",
    "category": "Starters",
    "isVeg": false,
    "price": 319,
    "description": "Crisp-fried chicken drumettes shaped into lollipops, served with zesty hot garlic dipping sauce.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-lollipop.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-9",
    "name": "Chicken Boti Kebab",
    "category": "Starters",
    "isVeg": false,
    "price": 329,
    "description": "Tender chicken boti bites steeped in Kashmiri red chilli and raw papaya marinade, charred over coal embers.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-10",
    "name": "Chicken Hariyali Kebab",
    "category": "Starters",
    "isVeg": false,
    "price": 369,
    "description": "Succulent chicken morsels infused with fresh mint, coriander, green chillies, and roasted cumin.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-hariyali.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-11",
    "name": "Chicken Kalimirch Kebab",
    "category": "Starters",
    "isVeg": false,
    "price": 330,
    "description": "Creamy tandoori chicken marinated in crushed Malabar black peppercorns, cashew paste, and fresh cream.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-12",
    "name": "Chicken Reshmi Kebab",
    "category": "Starters",
    "isVeg": false,
    "price": 329,
    "description": "Silken-smooth chicken kebabs tenderized with egg whites, clotted cream, and subtle saffron.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-malai-kebab.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-13",
    "name": "Chicken Achari Tikka",
    "category": "Starters",
    "isVeg": false,
    "price": 339,
    "description": "Tangy and bold chicken tikka infused with panch-phoran pickle spices and mustard oil.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-14",
    "name": "Chicken Garlic Kebab",
    "category": "Starters",
    "isVeg": false,
    "price": 359,
    "description": "Charcoal-roasted chicken skewers steeped in roasted golden garlic butter and crushed herbs.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-15",
    "name": "Tangdi Kebab [4 Pieces]",
    "category": "Starters",
    "isVeg": false,
    "price": 327,
    "description": "Four whole chicken drumsticks stuffed with spiced mince, slow-roasted in the clay oven with royal saffron.",
    "spicyLevel": 2,
    "isChefSpecial": true,
    "image": "/data/dishes/tangdi-kebab.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-16",
    "name": "Chicken Malai Kebab",
    "category": "Starters",
    "isVeg": false,
    "price": 419,
    "description": "Mild, decadent chicken cubes bathed in rich cardamom cream, cashew nut paste, and melted cheese.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-malai-kebab.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-17",
    "name": "Chicken Cheese Kebab",
    "category": "Starters",
    "isVeg": false,
    "price": 459,
    "description": "Double-layered succulent chicken kebabs stuffed with molten mozzarella and mild green herbs.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-18",
    "name": "Chicken Cutlet",
    "category": "Starters",
    "isVeg": false,
    "price": 249,
    "description": "Crispy golden-crumbed chicken patty seasoned with onion, ginger, and Mughlai spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-19",
    "name": "Chicken Hot Garlic",
    "category": "Starters",
    "isVeg": false,
    "price": 299,
    "description": "Juicy chicken bites tossed in a spicy, aromatic hot garlic and red pepper reduction.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-20",
    "name": "Tandoori Chicken",
    "category": "Starters",
    "isVeg": false,
    "price": 289,
    "description": "Traditional whole chicken marinated overnight in Kashmiri deghi mirch and mustard oil, roasted to smoky perfection.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/tandoori-chicken.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-21",
    "name": "Chicken Saty",
    "category": "Starters",
    "isVeg": false,
    "price": 349,
    "description": "Skewered grilled chicken fillets glazed with sweet-spicy peanut sauce and scallions.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-22",
    "name": "Honey Potato Chilli",
    "category": "Starters",
    "isVeg": true,
    "price": 209,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/honey-chilli-potato.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-23",
    "name": "Veg Manchurian",
    "category": "Starters",
    "isVeg": true,
    "price": 110,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/veg-manchurian.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-24",
    "name": "Paneer Chilli",
    "category": "Starters",
    "isVeg": true,
    "price": 159,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-chilli.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-25",
    "name": "Mushroom Chilli",
    "category": "Starters",
    "isVeg": true,
    "price": 159,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/mushroom-chilli.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-26",
    "name": "Corn Salt And Pepper",
    "category": "Starters",
    "isVeg": true,
    "price": 249,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/corn-salt-pepper.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-27",
    "name": "Paneer Tikka",
    "category": "Starters",
    "isVeg": true,
    "price": 289,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-28",
    "name": "Paneer Achari Tikka",
    "category": "Starters",
    "isVeg": true,
    "price": 299,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-29",
    "name": "Paneer Seekh Kebab",
    "category": "Starters",
    "isVeg": true,
    "price": 319,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-seekh-kebab.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-30",
    "name": "Mushroom Salt And Pepper",
    "category": "Starters",
    "isVeg": true,
    "price": 299,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/mushroom-chilli.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-31",
    "name": "Paneer Salt And Pepper",
    "category": "Starters",
    "isVeg": true,
    "price": 299,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-32",
    "name": "Baby Corn Chilli",
    "category": "Starters",
    "isVeg": true,
    "price": 249,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/corn-salt-pepper.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-33",
    "name": "Mushroom Crispy Chilli",
    "category": "Starters",
    "isVeg": true,
    "price": 279,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/mushroom-chilli.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-34",
    "name": "Baby Corn Paprika",
    "category": "Starters",
    "isVeg": true,
    "price": 265,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/corn-salt-pepper.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-35",
    "name": "Hara Bhara Kabab",
    "category": "Starters",
    "isVeg": true,
    "price": 299,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/hara-bhara-kabab.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-36",
    "name": "Paneer Cutlet",
    "category": "Starters",
    "isVeg": true,
    "price": 209,
    "description": "Crispy paneer cutlet with mild spices and seasoning.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-37",
    "name": "Paneer Popcorn",
    "category": "Starters",
    "isVeg": true,
    "price": 249,
    "description": "Bite-sized crispy paneer popcorn tossed with seasoning.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-38",
    "name": "Paneer Hot Garlic",
    "category": "Starters",
    "isVeg": true,
    "price": 319,
    "description": "Soft paneer tossed in a spicy hot garlic sauce.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-39",
    "name": "Paneer 65",
    "category": "Starters",
    "isVeg": true,
    "price": 269,
    "description": "Spicy paneer starter tossed with bold seasonings.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/paneer-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-40",
    "name": "Paneer Malai Kebab",
    "category": "Starters",
    "isVeg": true,
    "price": 329,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-malai-kebab.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-41",
    "name": "Veg Cheese Ball",
    "category": "Starters",
    "isVeg": true,
    "price": 319,
    "description": "Crispy vegetable cheese balls with a cheesy centre.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-42",
    "name": "Paneer Cheese Ball",
    "category": "Starters",
    "isVeg": true,
    "price": 329,
    "description": "Crispy paneer cheese balls filled with rich cheesy flavour.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-43",
    "name": "Paneer Saty",
    "category": "Starters",
    "isVeg": true,
    "price": 329,
    "description": "Flavourful paneer saty served with aromatic seasoning.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-44",
    "name": "Egg Masala",
    "category": "Main Course",
    "isVeg": false,
    "price": 159,
    "description": "Masala medium spicy",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/egg-curry.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-45",
    "name": "Chicken Tikka Masala",
    "category": "Main Course",
    "isVeg": false,
    "price": 499,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-46",
    "name": "Punjabi Chicken",
    "category": "Main Course",
    "isVeg": false,
    "price": 469,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-curry.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-47",
    "name": "Murgh Musallam",
    "category": "Main Course",
    "isVeg": false,
    "price": 599,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/murgh-musallam.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-48",
    "name": "Royal Special Chicken",
    "category": "Main Course",
    "isVeg": false,
    "price": 669,
    "description": "Delicious",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-curry.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-49",
    "name": "Chicken Mughlai",
    "category": "Main Course",
    "isVeg": false,
    "price": 479,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/murgh-musallam.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-50",
    "name": "Butter Chicken",
    "category": "Main Course",
    "isVeg": false,
    "price": 469,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/butter-chicken.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-51",
    "name": "Chicken Butter Masala",
    "category": "Main Course",
    "isVeg": false,
    "price": 419,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/butter-chicken.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-52",
    "name": "Chicken Do Pyaaza",
    "category": "Main Course",
    "isVeg": false,
    "price": 290,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/butter-chicken.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-53",
    "name": "Chicken Handi",
    "category": "Main Course",
    "isVeg": false,
    "price": 299,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/butter-chicken.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-54",
    "name": "Chicken Bharta",
    "category": "Main Course",
    "isVeg": false,
    "price": 389,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/butter-chicken.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-55",
    "name": "Kadhai Chicken",
    "category": "Main Course",
    "isVeg": false,
    "price": 305,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/kadhai-chicken.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-56",
    "name": "Dehati Chicken",
    "category": "Main Course",
    "isVeg": false,
    "price": 329,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/butter-chicken.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-57",
    "name": "Chicken Patiala",
    "category": "Main Course",
    "isVeg": false,
    "price": 319,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/butter-chicken.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-58",
    "name": "Dal Fry",
    "category": "Main Course",
    "isVeg": true,
    "price": 119,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/dal-tadka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-59",
    "name": "Dal Tadka",
    "category": "Main Course",
    "isVeg": true,
    "price": 79,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/dal-tadka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-60",
    "name": "Dal Makhani",
    "category": "Main Course",
    "isVeg": true,
    "price": 159,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/dal-makhani.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-61",
    "name": "Aloo Dum Bhojpuri",
    "category": "Main Course",
    "isVeg": true,
    "price": 99,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/aloo-dum.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-62",
    "name": "Aloo Matar",
    "category": "Main Course",
    "isVeg": true,
    "price": 110,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/aloo-dum.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-63",
    "name": "Mix Veg",
    "category": "Main Course",
    "isVeg": true,
    "price": 110,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/mix-veg.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-64",
    "name": "Matar Paneer",
    "category": "Main Course",
    "isVeg": true,
    "price": 129,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/matar-paneer.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-65",
    "name": "Paneer Masala",
    "category": "Main Course",
    "isVeg": true,
    "price": 199,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-66",
    "name": "Mushroom Chatpata",
    "category": "Main Course",
    "isVeg": true,
    "price": 229,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/mushroom-chilli.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-67",
    "name": "Palak Paneer",
    "category": "Main Course",
    "isVeg": true,
    "price": 130,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-68",
    "name": "Paneer Chatpata",
    "category": "Main Course",
    "isVeg": true,
    "price": 209,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-69",
    "name": "Paneer Do Pyaaza",
    "category": "Main Course",
    "isVeg": true,
    "price": 150,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-70",
    "name": "Kadhai Paneer",
    "category": "Main Course",
    "isVeg": true,
    "price": 159,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/kadhai-paneer.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-71",
    "name": "Mushroom Do Pyaaza",
    "category": "Main Course",
    "isVeg": true,
    "price": 160,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/mushroom-chilli.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-72",
    "name": "Paneer Handi",
    "category": "Main Course",
    "isVeg": true,
    "price": 169,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-73",
    "name": "Paneer Butter Masala",
    "category": "Main Course",
    "isVeg": true,
    "price": 199,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-74",
    "name": "Mushroom Butter Masala",
    "category": "Main Course",
    "isVeg": true,
    "price": 170,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/mushroom-chilli.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-75",
    "name": "Shahi Paneer",
    "category": "Main Course",
    "isVeg": true,
    "price": 359,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-76",
    "name": "Mushroom Handi",
    "category": "Main Course",
    "isVeg": true,
    "price": 170,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/mushroom-chilli.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-77",
    "name": "Paneer Tikka Masala",
    "category": "Main Course",
    "isVeg": true,
    "price": 399,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 2,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-tikka.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-78",
    "name": "Mushroom Punjabi",
    "category": "Main Course",
    "isVeg": true,
    "price": 200,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/mushroom-chilli.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-79",
    "name": "Punjabi Paneer",
    "category": "Main Course",
    "isVeg": true,
    "price": 209,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-80",
    "name": "Sweet Paneer Malai Kofta",
    "category": "Main Course",
    "isVeg": true,
    "price": 389,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-81",
    "name": "Salt Paneer Malai Kofta",
    "category": "Main Course",
    "isVeg": true,
    "price": 389,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-82",
    "name": "Paneer Lababdar Masala",
    "category": "Main Course",
    "isVeg": true,
    "price": 209,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-83",
    "name": "Veg Biryani",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 189,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-biryani.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-84",
    "name": "Paneer Biryani",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 199,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-biryani.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-85",
    "name": "Egg Biryani",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 199,
    "description": "Yummy",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-biryani.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-86",
    "name": "Chicken Biryani",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 269,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-biryani.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-87",
    "name": "Royal Special Biryani",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 399,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/chicken-biryani.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-88",
    "name": "Steamed Rice",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 109,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/jeera-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-89",
    "name": "Jeera Rice",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 139,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/jeera-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-90",
    "name": "Veg Pulao",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 189,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-pulao.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-91",
    "name": "Kashmiri Pulao",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 229,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-pulao.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-92",
    "name": "Egg Fried Rice",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 199,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-fried-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-93",
    "name": "Egg Schezwan Fried Rice",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 219,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-fried-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-94",
    "name": "Chicken Fried Rice",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 259,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-fried-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-95",
    "name": "Chicken Schezwan Fried Rice",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 269,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 3,
    "isChefSpecial": true,
    "image": "/data/dishes/chicken-fried-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-96",
    "name": "Mixed Fried Rice",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 269,
    "description": "Yummy",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-fried-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-97",
    "name": "Veg Noodles",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 159,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-hakka-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-98",
    "name": "Veg Hakka Noodles",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 169,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-hakka-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-99",
    "name": "Veg Schezwan Noodles",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 169,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/schezwan-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-100",
    "name": "Paneer Noodles",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 199,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-hakka-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-101",
    "name": "Veg Chilli Garlic Noodles",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 199,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-hakka-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-102",
    "name": "Egg Noodles",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 189,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-hakka-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-103",
    "name": "Chicken Noodles",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 219,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/chicken-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-104",
    "name": "Mix Noodles",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 249,
    "description": "Yummy",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-hakka-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-105",
    "name": "Chicken Schezwan Noodles",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 229,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/schezwan-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-106",
    "name": "Chicken Egg Noodles",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 229,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-107",
    "name": "Chicken Chilli Garlic Noodles",
    "category": "Biryani & Rice",
    "isVeg": false,
    "price": 239,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-108",
    "name": "Veg Fried Rice",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 159,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-fried-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-109",
    "name": "Veg Schezwan Fried Rice",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 179,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-fried-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-110",
    "name": "Paneer Fried Rice",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 229,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-fried-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-111",
    "name": "Special Veg Chilli Garlic Fried Rice",
    "category": "Biryani & Rice",
    "isVeg": true,
    "price": 229,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": true,
    "image": "/data/dishes/veg-fried-rice.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-112",
    "name": "Veg Grilled Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 89,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-113",
    "name": "Cheese Corn Grilled Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 119,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-114",
    "name": "Paneer Grilled Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 119,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-115",
    "name": "Egg Grilled Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 109,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-116",
    "name": "Chicken Grilled Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 119,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-117",
    "name": "Veg Grilled Cheese Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 109,
    "description": "Grilled sandwich loaded with vegetables and melted cheese.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-118",
    "name": "Veg Crispy Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 129,
    "description": "Crispy veg sandwich with flavorful stuffing.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-119",
    "name": "Paneer Grilled Cheese Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 129,
    "description": "Grilled sandwich filled with paneer and melted cheese.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-120",
    "name": "Paneer Crispy Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 159,
    "description": "Crispy sandwich stuffed with paneer and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-121",
    "name": "Mushroom Grilled Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 119,
    "description": "Grilled sandwich with a savory mushroom filling.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-122",
    "name": "Mushroom Grilled Cheese Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 129,
    "description": "Grilled sandwich with mushrooms and melted cheese.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-123",
    "name": "Mushroom Crispy Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 159,
    "description": "Crispy sandwich with seasoned mushroom stuffing.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-124",
    "name": "Chicken Grilled Cheese Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 129,
    "description": "Grilled sandwich loaded with juicy chicken and melted cheese.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-125",
    "name": "Chicken Crispy Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 169,
    "description": "Crispy chicken sandwich with flavorful filling.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-126",
    "name": "Sweet Corn Grilled Cheese Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 129,
    "description": "Grilled sandwich filled with sweet corn and melted cheese.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-127",
    "name": "Egg Grilled Cheese Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 119,
    "description": "Grilled sandwich loaded with egg and melted cheese.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-128",
    "name": "Egg Crispy Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 159,
    "description": "Crispy sandwich filled with egg and flavourful stuffing.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-129",
    "name": "Sweet Corn Crispy Sandwich",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 159,
    "description": "Crispy sandwich filled with sweet corn and savoury seasoning.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/grilled-sandwich.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-130",
    "name": "Veg Cheese Burger",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 129,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/burger.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-131",
    "name": "Paneer Cheese Burger",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 159,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/burger.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-132",
    "name": "Egg Cheese Burger",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 149,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/burger.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-133",
    "name": "Chicken Cheese Burger",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 179,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/burger.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-134",
    "name": "Paneer Fried Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 149,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-135",
    "name": "Veg Fried Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 129,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/veg-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-136",
    "name": "Veg Crispy Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 159,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-137",
    "name": "Veg Afghani Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 169,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-138",
    "name": "Veg Crispy Afghani Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 179,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-139",
    "name": "Paneer Crispy Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 169,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-140",
    "name": "Paneer Afghani Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 179,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-141",
    "name": "Paneer Crispy Afghani Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 199,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-142",
    "name": "Chicken Crispy Afghani Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 199,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-143",
    "name": "Chicken Afghani Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 179,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/chicken-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-144",
    "name": "Chicken Crispy Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 169,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-145",
    "name": "Chicken Fried Momos [5 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 149,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-momos.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-146",
    "name": "Egg Roll",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 79,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-147",
    "name": "Chicken Egg Roll",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 160,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-148",
    "name": "Chicken Roll",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 120,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-149",
    "name": "Chicken Cheese Roll",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 135,
    "description": "Soft roll loaded with juicy chicken and melted cheese.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-150",
    "name": "Chicken Sweet Corn Roll",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 145,
    "description": "Soft roll filled with chicken and sweet corn stuffing.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/chicken-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-151",
    "name": "Double Egg Roll",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 93,
    "description": "Soft roll loaded with double egg and flavourful seasoning.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/paneer-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-152",
    "name": "Veg Roll",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 79,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-153",
    "name": "Cheese Corn Roll",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 106,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-154",
    "name": "Paneer Roll",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 106,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-155",
    "name": "Veg Sweet Corn Roll",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 93,
    "description": "Soft roll stuffed with sweet corn and flavourful veggies.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-156",
    "name": "Mushroom Roll",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 105,
    "description": "Soft roll filled with spiced mushroom stuffing.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-roll.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-157",
    "name": "Onion Pakora",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 109,
    "description": "Yummy",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/pakora.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-158",
    "name": "French Fries",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 109,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/french-fries.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-159",
    "name": "Veg Pakora [6 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 120,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/pakora.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-160",
    "name": "Cheese French Fries",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 129,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/french-fries.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-161",
    "name": "Sweet Corn Masala",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 149,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/sweet-corn-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-162",
    "name": "Chilli French Fries",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 189,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/french-fries.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-163",
    "name": "Paneer Pakora [8 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 199,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/pakora.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-164",
    "name": "Egg Pakora [2 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 120,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/pakora.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-165",
    "name": "Chicken Popcorn",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 279,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/veg-hakka-noodles.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-166",
    "name": "Chicken Pakora [8 Pieces]",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 259,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/pakora.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-167",
    "name": "Sweet Corn Soup",
    "category": "Main Course",
    "isVeg": true,
    "price": 109,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/sweet-corn-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-168",
    "name": "Veg Manchow Soup",
    "category": "Main Course",
    "isVeg": true,
    "price": 145,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/manchow-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-169",
    "name": "Tomato Soup",
    "category": "Main Course",
    "isVeg": true,
    "price": 109,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/manchow-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-170",
    "name": "Veg Hot And Sour Soup",
    "category": "Main Course",
    "isVeg": true,
    "price": 120,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/hot-and-sour-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-171",
    "name": "Veg Clear Soup",
    "category": "Main Course",
    "isVeg": true,
    "price": 110,
    "description": "Light and comforting clear soup with fresh vegetables.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/manchow-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-172",
    "name": "Veg Soup",
    "category": "Main Course",
    "isVeg": true,
    "price": 90,
    "description": "Comforting vegetable soup with mild and balanced flavours.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/manchow-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-173",
    "name": "Veg Mushroom Soup",
    "category": "Main Course",
    "isVeg": true,
    "price": 135,
    "description": "Warm vegetable soup with mushrooms and comforting flavours.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/manchow-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-174",
    "name": "Veg Paneer Soup",
    "category": "Main Course",
    "isVeg": true,
    "price": 135,
    "description": "Warm vegetable soup served with soft paneer cubes.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/manchow-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-175",
    "name": "Chicken Manchow Soup",
    "category": "Main Course",
    "isVeg": false,
    "price": 199,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/manchow-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-176",
    "name": "Chicken Hot And Sour Soup",
    "category": "Main Course",
    "isVeg": false,
    "price": 179,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 3,
    "isChefSpecial": false,
    "image": "/data/dishes/hot-and-sour-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-177",
    "name": "Chicken Corn Soup",
    "category": "Main Course",
    "isVeg": false,
    "price": 179,
    "description": "Tender succulent meat preparation cooked with signature herbs and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/sweet-corn-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-178",
    "name": "Chicken Clear Soup",
    "category": "Main Course",
    "isVeg": false,
    "price": 169,
    "description": "Light and comforting clear chicken soup with mild seasoning.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/manchow-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-179",
    "name": "Chicken Soup",
    "category": "Main Course",
    "isVeg": false,
    "price": 159,
    "description": "Warm and flavourful chicken soup made with comforting spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/manchow-soup.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-180",
    "name": "Tandoori Roti",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 19,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/tandoori-roti.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-181",
    "name": "Tandoori Butter Roti",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 29,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/tandoori-roti.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-182",
    "name": "Plain Naan",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 39,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/butter-naan.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-183",
    "name": "Onion Paratha",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 69,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/laccha-paratha.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-184",
    "name": "Butter Naan",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 49,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/butter-naan.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-185",
    "name": "Laccha Paratha",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 39,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/laccha-paratha.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-186",
    "name": "Stuffed Naan",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 89,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/butter-naan.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-187",
    "name": "Paneer Paratha",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 79,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-188",
    "name": "Garlic Naan",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 79,
    "description": "Soft naan topped with garlic and baked in tandoor.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/garlic-naan.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-189",
    "name": "Chicken Mughlai Paratha",
    "category": "Tandoori & Breads",
    "isVeg": false,
    "price": 199,
    "description": "Layered paratha stuffed with spiced chicken filling.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/murgh-musallam.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-190",
    "name": "Paneer Mughlai Paratha",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 189,
    "description": "Layered paratha stuffed with soft paneer and spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/murgh-musallam.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-191",
    "name": "Mushroom Mughlai Paratha",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 199,
    "description": "Layered paratha stuffed with seasoned mushroom filling.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/murgh-musallam.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-192",
    "name": "Aloo Paratha",
    "category": "Tandoori & Breads",
    "isVeg": true,
    "price": 69,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/laccha-paratha.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-193",
    "name": "Mix Raita",
    "category": "Main Course",
    "isVeg": true,
    "price": 66,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-194",
    "name": "Boondi Raita",
    "category": "Main Course",
    "isVeg": true,
    "price": 52,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-195",
    "name": "Onion Salad",
    "category": "Main Course",
    "isVeg": true,
    "price": 39,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-196",
    "name": "Green Salad",
    "category": "Main Course",
    "isVeg": true,
    "price": 67,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-197",
    "name": "Special Salad",
    "category": "Main Course",
    "isVeg": true,
    "price": 134,
    "description": "Fresh salad made with seasonal vegetables and light seasoning.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/paneer-butter-masala.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-198",
    "name": "Lemonade Mocktail",
    "category": "Beverages",
    "isVeg": true,
    "price": 79,
    "description": "[Non Alcoholic]",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/lemonade.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-199",
    "name": "Mango Mocktail",
    "category": "Beverages",
    "isVeg": true,
    "price": 79,
    "description": "[Non Alcoholic]",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/mango-mocktail.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-200",
    "name": "Strawberry Mocktail",
    "category": "Beverages",
    "isVeg": true,
    "price": 79,
    "description": "[Non Alcoholic]",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-201",
    "name": "Orange Mocktail",
    "category": "Beverages",
    "isVeg": true,
    "price": 79,
    "description": "[Non Alcoholic]",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-202",
    "name": "Fresh Lime Soda",
    "category": "Beverages",
    "isVeg": true,
    "price": 79,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/lemonade.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-203",
    "name": "Green Apple Mocktail",
    "category": "Beverages",
    "isVeg": true,
    "price": 79,
    "description": "[Non Alcoholic]",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-204",
    "name": "Virgin Mojito",
    "category": "Beverages",
    "isVeg": true,
    "price": 79,
    "description": "[Non Alcoholic]",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-205",
    "name": "Blue Lagoon Mocktail",
    "category": "Beverages",
    "isVeg": true,
    "price": 79,
    "description": "[Non Alcoholic]",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/blue-lagoon.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-206",
    "name": "Kiwi Blast Mocktail",
    "category": "Beverages",
    "isVeg": true,
    "price": 79,
    "description": "[Non Alcoholic]",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-207",
    "name": "Strawberry Shake",
    "category": "Beverages",
    "isVeg": true,
    "price": 129,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-208",
    "name": "Vanilla Shake",
    "category": "Beverages",
    "isVeg": true,
    "price": 129,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-209",
    "name": "KitKat Shake",
    "category": "Beverages",
    "isVeg": true,
    "price": 129,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-210",
    "name": "Butterscotch Shake",
    "category": "Beverages",
    "isVeg": true,
    "price": 129,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-211",
    "name": "Chocolate Shake",
    "category": "Beverages",
    "isVeg": true,
    "price": 129,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-212",
    "name": "Oreo Shake",
    "category": "Beverages",
    "isVeg": true,
    "price": 129,
    "description": "Delicious chef-crafted vegetarian delicacy prepared with authentic Indian spices.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-213",
    "name": "Cold Coffee With Ice Cream",
    "category": "Beverages",
    "isVeg": true,
    "price": 159,
    "description": "Yummy",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/virgin-mojito.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-214",
    "name": "White Sauce Pasta",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 209,
    "description": "Pasta tossed in a creamy and flavourful white sauce.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/pasta.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-215",
    "name": "Red Sauce Pasta",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 239,
    "description": "Pasta tossed in a rich and tangy red sauce.",
    "spicyLevel": 1,
    "isChefSpecial": true,
    "image": "/data/dishes/pasta.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-216",
    "name": "Corn Pasta",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 169,
    "description": "Pasta tossed with sweet corn in flavourful seasoning.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/pasta.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-217",
    "name": "Chilly Pasta",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 135,
    "description": "Pasta tossed with chilli and savoury seasonings.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/pasta.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-218",
    "name": "Mushroom Pasta",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 209,
    "description": "Pasta tossed with mushrooms in a flavourful sauce.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/pasta.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-219",
    "name": "Chicken Pasta",
    "category": "Chinese & Snacks",
    "isVeg": false,
    "price": 239,
    "description": "Pasta tossed with juicy chicken in a flavourful sauce.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/pasta.jpg",
    "serves": "1-2 Persons"
  },
  {
    "id": "m-220",
    "name": "Paneer Pasta",
    "category": "Chinese & Snacks",
    "isVeg": true,
    "price": 209,
    "description": "Pasta tossed with soft paneer in a flavourful sauce.",
    "spicyLevel": 1,
    "isChefSpecial": false,
    "image": "/data/dishes/pasta.jpg",
    "serves": "1-2 Persons"
  }
] as MenuItem[],

  seatingOptions: [
    {
      id: "maharaja",
      name: "Maharaja Family Chamber",
      description: "Exclusive air-conditioned dining area with comfortable velvet seating for family gatherings up to 12 guests.",
      badge: "Family & Groups"
    },
    {
      id: "courtyard",
      name: "Main Royal Hall",
      description: "Dine under warm chandeliers with gentle background music and attentive table service.",
      badge: "Most Popular"
    },
    {
      id: "terrace",
      name: "Cozy Couple Corner",
      description: "Private booth seating perfect for intimate dinners, dates, and celebrations.",
      badge: "Couples & Dates"
    }
  ]
};
