// Auto-generated configuration directly sourced from data/royal-rasoi.json
export interface MenuItem {
  id: string;
  name: string;
  hindiName?: string;
  category: string;
  subCategory?: string;
  isVeg: boolean;
  price: number;
  description: string;
  spicyLevel: 1 | 2 | 3;
  isChefSpecial?: boolean;
  image: string;
  serves: string;
}

export interface Review {
  id: string;
  guestName: string;
  city: string;
  rating: number;
  comment: string;
  date: string;
  dishLoved: string;
  images?: string[];
}

export interface CustomerPhoto {
  url: string;
  title: string;
  author: string;
}

export const royalConfig = {
  restaurant: {
    name: "The Royal Rasoi",
    tagline: "Flavors for Royalty • Authentic North Indian & Chinese Cuisine",
    subtitle: "Fine Dining Restaurant in Sadikpur, Patna",
    establishedYear: "2018",
    rating: "4.7",
    totalReviews: "520+ Google Reviews",
    guestsServed: "3,850+ Gourmands Served",
    priceForTwo: "INR 500",
    address: "City Court, near Smart Point, Sadikpur, Patna, Bihar 800007",
    phone: "099056 04856",
    googleMapsUrl: "https://www.google.com/maps/place/The+Royal+Rasoi/@25.6063597,75.4530912,6z/data=!4m10!1m2!2m1!1sroyal+rasoi!3m6!1s0x39ed5f7b28401aff:0x48badbd4cd527fe2!8m2!3d25.6063597!4d85.2089506!15sCgtyb3lhbCByYXNvaZIBEWluZGlhbl9yZXN0YXVyYW504AEA!16s%2Fg%2F11yjlngqmv?hl=en-IN&entry=ttu",
    swiggyUrl: "https://www.swiggy.com/restaurants/1309308/dineout",
    hours: {
      lunch: "11:00 AM – 04:00 PM",
      dinner: "04:00 PM – 10:30 PM",
      days: "Open All 7 Days"
    },
    amenities: ["Parking", "Air-Conditioned", "Cozy Celebrations (10-12)", "Takeaway & Delivery", "SwiggyPay accepted"],
    chef: {
      name: "The Royal Kitchen Team",
      title: "Master Culinary Khansamas",
      experience: "Authentic Mughlai & Awadhi Heritage",
      bio: "Mastering the culinary art of slow-cooked Dum Handis, charcoal tandoori grills, and hand-ground spices to deliver authentic flavors at City Court, Sadikpur, Patna."
    }
  },

  menuPages: [
  "/data/menu/menu-page-1.JPG",
  "/data/menu/menu-page-2.JPG",
  "/data/menu/menu-page-3.JPG",
  "/data/menu/menu-page-4.JPG",
  "/data/menu/menu-page-5.JPG",
  "/data/menu/menu-page-6.JPG",
  "/data/menu/menu-page-7.JPG"
],

  customerPhotos: [
  {
    "url": "/data/reviews/review-image-1.jpg",
    "title": "Neon Photo Wall: 'You're in the Right Place'",
    "author": "Cafe Decor • Selfie Spot"
  },
  {
    "url": "/data/reviews/review-image-2.jpg",
    "title": "Chicken Handi Gravy with Fresh Cream",
    "author": "Main Course • Handi Special"
  },
  {
    "url": "/data/reviews/review-image-3.jpg",
    "title": "Butter Naan & Rich Chicken Curry Platter",
    "author": "Dining Setup • Tandoori Feast"
  },
  {
    "url": "/data/reviews/review-image-4.jpg",
    "title": "Crispy Clay-Tandoor Butter Naan",
    "author": "Tandoor • Freshly Baked"
  },
  {
    "url": "/data/reviews/review-image-6.jpg",
    "title": "Illuminated Ring Chandelier & Greenery",
    "author": "Ambience • Cafe Interiors"
  },
  {
    "url": "/data/reviews/review-image-7.jpg",
    "title": "Arched Floral Mirror Selfie Corner",
    "author": "Cafe Decor • Photo Corner"
  },
  {
    "url": "/data/reviews/review-image-8.jpg",
    "title": "Air-Conditioned Dining Hall & Seating",
    "author": "Ambience • Family Dining"
  },
  {
    "url": "/data/reviews/review-image-9.jpg",
    "title": "Crispy Chilli Chicken Dry with Peppers",
    "author": "Chinese & Starters • Wok Tossed"
  },
  {
    "url": "/data/reviews/review-image-10.jpg",
    "title": "Rich Chicken Butter Masala with Cashews",
    "author": "Main Course • Makhani Special"
  }
] as CustomerPhoto[],

  reviews: [
  {
    "id": "r-1",
    "guestName": "Amarjeet_Yadav",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Food is tasty, delicious and pocket friendly. You should visit once.",
    "date": "Edited 4 months ago",
    "dishLoved": "Chicken Tikka & Biryani",
    "images": [
      "/data/reviews/review-image-1.jpg",
      "/data/reviews/review-image-2.jpg"
    ]
  },
  {
    "id": "r-2",
    "guestName": "Gourav kumar",
    "city": "Sadikpur, Patna",
    "rating": 1,
    "comment": "Reported a serious quality issue with Chicken Lollipop.",
    "date": "a month ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  },
  {
    "id": "r-3",
    "guestName": "Rameez Ahmad",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Good people, good service, good place, good view and comfortable seating.",
    "date": "a year ago",
    "dishLoved": "Special Tandoori & Kebabs",
    "images": [
      "/data/reviews/review-image-3.jpg",
      "/data/reviews/review-image-4.jpg"
    ]
  },
  {
    "id": "r-4",
    "guestName": "Ravi Gupta",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Delicious food and very professional staff. Must try food.",
    "date": "6 months ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  },
  {
    "id": "r-5",
    "guestName": "Dipanshu Sharma",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Best restaurant.",
    "date": "6 months ago",
    "dishLoved": "North Indian Specialties",
    "images": [
      "/data/reviews/review-image-6.jpg"
    ]
  },
  {
    "id": "r-6",
    "guestName": "Rabia",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Wonderful experience, delicious food, cozy atmosphere and warm service.",
    "date": "a year ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  },
  {
    "id": "r-7",
    "guestName": "AK J",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "The food they serve is very awesome and delicious.",
    "date": "2 months ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  },
  {
    "id": "r-8",
    "guestName": "Anubhavi",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Cafe was good and affordable, with good employee behaviour.",
    "date": "7 months ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  },
  {
    "id": "r-9",
    "guestName": "Tripti Chawla",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Awesome ambience. Food was too good.",
    "date": "a year ago",
    "dishLoved": "Tandoori Starters & Ambience",
    "images": [
      "/data/reviews/review-image-7.jpg",
      "/data/reviews/review-image-8.jpg"
    ]
  },
  {
    "id": "r-10",
    "guestName": "Abhi decoration Agency",
    "city": "Sadikpur, Patna",
    "rating": 5,
    "comment": "Very good and very tasty food.",
    "date": "9 months ago",
    "dishLoved": "North Indian Specialties",
    "images": []
  }
] as Review[],

  menu: [
      {
          "id": "m-1",
          "name": "Royal Spl. Veg Thali",
          "category": "Combos & Thali",
          "subCategory": "Thali",
          "isVeg": true,
          "price": 269,
          "description": "Butter Tawa Roti (3 Pcs), Jeera Rice, Paneer butter Masala, Mix Veg, Dal, Salad, Raita, Sweets, Papad & pickle.",
          "spicyLevel": 1,
          "isChefSpecial": true,
          "image": "/data/dishes/royal-spl-veg-thali.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-2",
          "name": "Royal Spl. Non Veg Thali",
          "category": "Combos & Thali",
          "subCategory": "Thali",
          "isVeg": false,
          "price": 335,
          "description": "Butter Tawa Roti (2 Pcs), Jeera Rice, Chicken butter Masala (2 Pcs), Salad, Raita, Sweets, Papad & pickle.",
          "spicyLevel": 1,
          "isChefSpecial": true,
          "image": "/data/dishes/royal-spl-non-veg-thali.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-3",
          "name": "Snacks Combo",
          "category": "Combos & Thali",
          "subCategory": "Budget Friendly Combo",
          "isVeg": true,
          "price": 179,
          "description": "French fries + Veg Grilled Sandwich + Fried Momo (2 Pcs) + cold drink.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/snacks-combo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-4",
          "name": "Chinese Combo (Veg)",
          "category": "Combos & Thali",
          "subCategory": "Budget Friendly Combo",
          "isVeg": true,
          "price": 336,
          "description": "Noodles + Fried Rice + Paneer chilly (2Pcs) + Manchurian (2 Pcs) + Fried Momo (2Pcs) + Cold drink.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chinese-combo-veg.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-5",
          "name": "Chinese Combo (Non Veg)",
          "category": "Combos & Thali",
          "subCategory": "Budget Friendly Combo",
          "isVeg": false,
          "price": 399,
          "description": "Chicken Noodles + Butter Naan + Chicken chilly (4Pcs) + Lollipop (2 Pcs) + mojito.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chinese-combo-non-veg.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-6",
          "name": "Blue Lagoon",
          "category": "Beverages & Soups",
          "subCategory": "Mocktail",
          "isVeg": true,
          "price": 79,
          "description": "Chilled sparkling blue curacao cooler with fresh lemon zest, mint sprigs, and soda.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/blue-lagoon.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-7",
          "name": "Kiwi Blast",
          "category": "Beverages & Soups",
          "subCategory": "Mocktail",
          "isVeg": true,
          "price": 79,
          "description": "Zesty green kiwi cooler blended with crushed mint leaves, lime juice, and sparkling fizz.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/kiwi-blast.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-8",
          "name": "Virgin Mojito",
          "category": "Beverages & Soups",
          "subCategory": "Mocktail",
          "isVeg": true,
          "price": 79,
          "description": "Classic Havana-style refresher with muddled fresh garden mint, lime wedges, and bubbly soda.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/virgin-mojito.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-9",
          "name": "Green Apple",
          "category": "Beverages & Soups",
          "subCategory": "Mocktail",
          "isVeg": true,
          "price": 79,
          "description": "Crisp tart green apple syrup infused with lemon juice and chilled effervescent soda.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/green-apple.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-10",
          "name": "Fresh Lime Soda",
          "category": "Beverages & Soups",
          "subCategory": "Mocktail",
          "isVeg": true,
          "price": 79,
          "description": "Refreshing fresh-squeezed lime juice served sweet, salted, or mixed over crushed ice.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/fresh-lime-soda.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-11",
          "name": "Lemonade",
          "category": "Beverages & Soups",
          "subCategory": "Mocktail",
          "isVeg": true,
          "price": 79,
          "description": "Traditional thirst-quenching sweet and tangy lemon refresher with roasted cumin pinch.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/lemonade.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-12",
          "name": "Mango",
          "category": "Beverages & Soups",
          "subCategory": "Mocktail",
          "isVeg": true,
          "price": 79,
          "description": "Tropical sweet Alphonso mango nectar lightly spritzed with sparkling lime soda.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/mango.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-13",
          "name": "Strawberry",
          "category": "Beverages & Soups",
          "subCategory": "Mocktail",
          "isVeg": true,
          "price": 79,
          "description": "Luscious strawberry puree shaken with ice, fresh mint, and fizzy soda splash.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/strawberry.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-14",
          "name": "Orange",
          "category": "Beverages & Soups",
          "subCategory": "Mocktail",
          "isVeg": true,
          "price": 79,
          "description": "Vibrant citrus Valencia orange cooler with a hint of tangy rock salt and mint.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/orange.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-15",
          "name": "Oreo Shake",
          "category": "Beverages & Soups",
          "subCategory": "Shake",
          "isVeg": true,
          "price": 129,
          "description": "Thick velvety shake blended with crunchy Oreo cookies, dark chocolate fudge, and rich milk.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/oreo-shake.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-16",
          "name": "Chocolate Shake",
          "category": "Beverages & Soups",
          "subCategory": "Shake",
          "isVeg": true,
          "price": 129,
          "description": "Decadent creamy shake made with pure Dutch cocoa, molten chocolate drizzle, and vanilla cream.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chocolate-shake.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-17",
          "name": "KitKat Shake",
          "category": "Beverages & Soups",
          "subCategory": "Shake",
          "isVeg": true,
          "price": 129,
          "description": "Crisp KitKat chocolate wafer bars blended into rich milk and topped with wafer crunch.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/kitkat-shake.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-18",
          "name": "Vanilla Shake",
          "category": "Beverages & Soups",
          "subCategory": "Shake",
          "isVeg": true,
          "price": 129,
          "description": "Silky smooth classic Madagascar vanilla bean shake whipped to creamy, frothy perfection.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/vanilla-shake.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-19",
          "name": "Strawberry Shake",
          "category": "Beverages & Soups",
          "subCategory": "Shake",
          "isVeg": true,
          "price": 129,
          "description": "Fresh berry-infused pink strawberry milkshake topped with whipped cream and syrup.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/strawberry-shake.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-20",
          "name": "ButterScotch Shake",
          "category": "Beverages & Soups",
          "subCategory": "Shake",
          "isVeg": true,
          "price": 129,
          "description": "Rich golden butterscotch milkshake laced with crunchy caramelized praline crumbles.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/butterscotch-shake.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-21",
          "name": "Cold Coffee with Ice cream",
          "category": "Beverages & Soups",
          "subCategory": "Shake",
          "isVeg": true,
          "price": 159,
          "description": "Strong espresso brewed and blended with chilled milk, topped with a scoop of vanilla ice cream.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/cold-coffee-with-ice-cream.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-22",
          "name": "Egg Masala",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 109,
          "description": "Hard-boiled farm eggs cooked in a rich onion-tomato gravy with roasted garam masala.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/egg-masala.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-23",
          "name": "Chicken Do Pyaza",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 290,
          "description": "Succulent chicken pieces cooked with double the onions in a rich caramelized semi-dry gravy.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-do-pyaza.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-24",
          "name": "Chicken Handi",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 299,
          "description": "Traditional slow-cooked chicken in an earthen handi with fragrant potli spices and fresh cream.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-handi.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-25",
          "name": "Chicken Bharta",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 301,
          "description": "Shredded smoked chicken simmered in a velvety egg-infused cashew and tomato gravy.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-bharta.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-26",
          "name": "Kadhai Chicken",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 305,
          "description": "Tender chicken tossed in a cast-iron kadhai with crunchy bell peppers, coriander seeds, and dry red chillies.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/kadhai-chicken.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-27",
          "name": "Chicken Butter Masala",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 317,
          "description": "Chicken chunks simmered in a silky, mildly sweet tomato-butter gravy with kasuri methi.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-butter-masala.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-28",
          "name": "Dehati Chicken",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 329,
          "description": "Rustic Bihari-style chicken curry cooked with whole garlic cloves, mustard oil, and crushed spices.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/dehati-chicken.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-29",
          "name": "Butter Chicken",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 331,
          "description": "The timeless royal classic: tandoori chicken simmered in rich makhani gravy with pure butter.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/butter-chicken.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-30",
          "name": "Chicken Mughlai",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 343,
          "description": "Royal Awadhi chicken preparation cooked in a creamy almond-cashew paste with saffron hints.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-mughlai.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-31",
          "name": "Chicken Tikka Masala",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 330,
          "description": "Charcoal-grilled chicken tikka morsels tossed in a spicy, vibrant tomato-onion masala gravy.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-tikka-masala.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-32",
          "name": "Punjabi Chicken",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 345,
          "description": "Robust North Indian style spicy chicken curry flavored with ginger juliennes and fresh green chillies.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/punjabi-chicken.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-33",
          "name": "Murgh Musallam",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 599,
          "description": "Grand whole chicken slow-cooked with rich Mughlai spices, boiled egg stuffing, and royal saffron gravy.",
          "spicyLevel": 1,
          "isChefSpecial": true,
          "image": "/data/dishes/murgh-musallam.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-34",
          "name": "Royal Spl. Chicken",
          "category": "Curries & Chinese",
          "subCategory": "Indian (Chicken)",
          "isVeg": false,
          "price": 600,
          "description": "Our master chef special chicken preparation featuring secret spice blend and slow-simmered rich gravy.",
          "spicyLevel": 1,
          "isChefSpecial": true,
          "image": "/data/dishes/royal-spl-chicken.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-35",
          "name": "Tandoori Roti",
          "category": "Tandoori Breads",
          "subCategory": "Roti & Bread",
          "isVeg": true,
          "price": 15,
          "description": "Whole wheat flatbread slapped on the clay tandoor walls and baked to crisp perfection.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/tandoori-roti.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-36",
          "name": "Tandoori Butter Roti",
          "category": "Tandoori Breads",
          "subCategory": "Roti & Bread",
          "isVeg": true,
          "price": 20,
          "description": "Hot whole wheat tandoori roti generously brushed with creamy dairy butter.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/tandoori-butter-roti.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-37",
          "name": "Plain Naan",
          "category": "Tandoori Breads",
          "subCategory": "Roti & Bread",
          "isVeg": true,
          "price": 35,
          "description": "Soft and pillowy leavened refined flour bread baked fresh in the glowing clay tandoor.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/plain-naan.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-38",
          "name": "Butter Naan",
          "category": "Tandoori Breads",
          "subCategory": "Roti & Bread",
          "isVeg": true,
          "price": 40,
          "description": "Tender clay oven-baked naan bread smothered in golden melted butter.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/butter-naan.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-39",
          "name": "Lachha Paratha",
          "category": "Tandoori Breads",
          "subCategory": "Roti & Bread",
          "isVeg": true,
          "price": 46,
          "description": "Multi-layered flaky whole wheat paratha crisped on the tandoor with pure ghee.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/lachha-paratha.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-40",
          "name": "Aloo Paratha",
          "category": "Tandoori Breads",
          "subCategory": "Roti & Bread",
          "isVeg": true,
          "price": 40,
          "description": "Tandoori paratha stuffed with spiced mashed potatoes, green chillies, and fresh coriander.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/aloo-paratha.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-41",
          "name": "Onion(pyaaz) Paratha",
          "category": "Tandoori Breads",
          "subCategory": "Roti & Bread",
          "isVeg": true,
          "price": 35,
          "description": "Crisp tandoori paratha stuffed with finely chopped spiced onions and ajwain.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/onionpyaaz-paratha.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-42",
          "name": "Stuffed Naan",
          "category": "Tandoori Breads",
          "subCategory": "Roti & Bread",
          "isVeg": true,
          "price": 65,
          "description": "Leavened naan bread generously filled with spiced mashed vegetables, herbs, and paneer.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/stuffed-naan.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-43",
          "name": "Paneer Paratha",
          "category": "Tandoori Breads",
          "subCategory": "Roti & Bread",
          "isVeg": true,
          "price": 68,
          "description": "Flaky golden tandoori paratha packed with seasoned grated cottage cheese and herbs.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-paratha.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-44",
          "name": "Steamed Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 70,
          "description": "Fluffy, long-grain basmati rice steamed to tender perfection.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/steamed-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-45",
          "name": "Jeera Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 95,
          "description": "Fragrant aged basmati rice tempered with aromatic cumin seeds and pure desi ghee.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/jeera-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-46",
          "name": "Veg Fried Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 130,
          "description": "Wok-tossed basmati rice with finely diced carrots, beans, cabbage, and light soya sauce.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-fried-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-47",
          "name": "Veg Schezwan Fried Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 140,
          "description": "Spicy wok-tossed fried rice infused with fiery red Schezwan pepper sauce and spring onions.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-schezwan-fried-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-48",
          "name": "Veg Pulao",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 150,
          "description": "Mildly spiced aromatic basmati rice cooked with fresh seasonal vegetables and whole spices.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-pulao.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-49",
          "name": "Egg Fried Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": false,
          "price": 145,
          "description": "Wok-fried fluffy basmati tossed with golden scrambled eggs, spring onions, and white pepper.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/egg-fried-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-50",
          "name": "Egg Schezwan Fried Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": false,
          "price": 160,
          "description": "Egg fried rice elevated with spicy in-house Schezwan sauce and crunchy bell peppers.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/egg-schezwan-fried-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-51",
          "name": "Spl Veg Chilli Garlic Fried Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 170,
          "description": "Aromatic rice fried with roasted golden garlic cloves, fiery green chillies, and vegetables.",
          "spicyLevel": 2,
          "isChefSpecial": true,
          "image": "/data/dishes/spl-veg-chilli-garlic-fried-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-52",
          "name": "Paneer Fried Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 160,
          "description": "Savory fried rice tossed with golden fried paneer cubes, vegetables, and oriental seasoning.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-fried-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-53",
          "name": "Chicken Fried Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": false,
          "price": 162,
          "description": "Tender chicken bites and fluffy rice wok-tossed with spring onions, egg ribbons, and soy sauce.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-fried-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-54",
          "name": "Chicken Schezwan Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": false,
          "price": 185,
          "description": "Fiery wok-fried rice with diced chicken, Schezwan paste, and spicy red chillies.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-schezwan-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-55",
          "name": "Mixed Fried Rice",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 199,
          "description": "Loaded fried rice featuring a delicious trio of chicken, scrambled egg, and fresh garden veggies.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/mixed-fried-rice.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-56",
          "name": "Kashmiri Pulao",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 210,
          "description": "Sweet and aromatic saffron basmati rice garnished with dry fruits, nuts, and fresh pomegranate.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/kashmiri-pulao.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-57",
          "name": "Veg Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 109,
          "description": "Classic stir-fried thin wheat noodles with crunchy julienned cabbage, carrots, and soy seasoning.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-58",
          "name": "Veg Hakka Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 135,
          "description": "Street-style Hakka noodles tossed with bell peppers, shredded cabbage, and aromatic spices.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-hakka-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-59",
          "name": "Veg Schezwan Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 147,
          "description": "Spicy Schezwan noodles tossed with fiery red chilli sauce and crunchy spring vegetables.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-schezwan-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-60",
          "name": "Veg Chilli Garlic Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 161,
          "description": "Savory noodles infused with deeply browned garlic, fresh green chillies, and soya sauce.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-chilli-garlic-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-61",
          "name": "Paneer Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 159,
          "description": "Wok-tossed noodles loaded with soft paneer cubes, crunchy peppers, and oriental spices.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-62",
          "name": "Egg Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": false,
          "price": 172,
          "description": "Hakka noodles tossed with fluffy scrambled egg ribbons, onions, and spicy seasoning.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/egg-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-63",
          "name": "Chicken Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": false,
          "price": 188,
          "description": "Stir-fried noodles loaded with shredded seasoned chicken, spring onions, and savoury sauces.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-64",
          "name": "Mix Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": true,
          "price": 197,
          "description": "Wok noodles tossed with seasoned chicken, egg scramble, and fresh vegetables.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/mix-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-65",
          "name": "Chicken Schezwan Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": false,
          "price": 198,
          "description": "Spicy chicken noodles coated in zesty homemade Schezwan sauce with scallions.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-schezwan-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-66",
          "name": "Chicken Egg Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": false,
          "price": 214,
          "description": "Rich noodles tossed with both tender chicken shreds and scrambled egg bits.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-egg-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-67",
          "name": "Chicken Chilli Garlic Noodles",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Rice & Noodles",
          "isVeg": false,
          "price": 238,
          "description": "Spicy noodles bursting with pungent roasted garlic and tender chicken morsels.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-chilli-garlic-noodles.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-68",
          "name": "Veg Biryani",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Biryani",
          "isVeg": true,
          "price": 160,
          "description": "Fragrant basmati rice layered with spiced seasonal vegetables, saffron milk, and fried onions.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-biryani.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-69",
          "name": "Egg Biryani",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Biryani",
          "isVeg": false,
          "price": 172,
          "description": "Dum-cooked aromatic basmati rice served with two golden roasted eggs and spicy salan.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/egg-biryani.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-70",
          "name": "Paneer Biryani",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Biryani",
          "isVeg": true,
          "price": 175,
          "description": "Tender marinated cottage cheese cubes dum-cooked with aged basmati, mint, and royal spices.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-biryani.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-71",
          "name": "Chicken Biryani",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Biryani",
          "isVeg": false,
          "price": 250,
          "description": "Authentic Awadhi dum biryani with succulent chicken pieces, saffron basmati, and boiled egg.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-biryani.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-72",
          "name": "Royal Spl. Biryani",
          "category": "Rice, Biryani & Noodles",
          "subCategory": "Biryani",
          "isVeg": true,
          "price": 399,
          "description": "Our chef signature feast biryani loaded with double chicken, egg, dry fruits, and saffron.",
          "spicyLevel": 1,
          "isChefSpecial": true,
          "image": "/data/dishes/royal-spl-biryani.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-73",
          "name": "French Fries",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 95,
          "description": "Crisp golden salted potato fingers fried to perfection, served with tangy tomato ketchup.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/french-fries.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-74",
          "name": "Cheese French Fries",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 115,
          "description": "Crispy golden fries smothered in warm molten cheddar cheese sauce and oregano.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/cheese-french-fries.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-75",
          "name": "Sweet Corn masala",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 125,
          "description": "Steamed tender sweet corn kernels tossed with butter, chatpata chaat masala, and lemon.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/sweet-corn-masala.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-76",
          "name": "Onion(pyaaz) Pakora",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 70,
          "description": "Crisp golden fritters made with sliced onions, carom seeds, and green chillies in gram flour.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/onionpyaaz-pakora.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-77",
          "name": "Egg Pakora",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": false,
          "price": 85,
          "description": "Boiled egg halves dipped in seasoned chickpea batter, golden fried with chaat masala.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/egg-pakora.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-78",
          "name": "Veg Pakora",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 95,
          "description": "Assorted vegetable fritters of potato, cauliflower, and onions fried crisp and piping hot.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-pakora.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-79",
          "name": "Paneer Pakora (8pcs)",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 135,
          "description": "Thick fresh cottage cheese cubes seasoned with ajwain and batter-fried to golden crunch.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-pakora-8pcs.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-80",
          "name": "Chicken Pakora (8Pcs)",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": false,
          "price": 200,
          "description": "Juicy chicken bites marinated in royal spices and deep-fried in a crunchy spiced batter.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-pakora-8pcs.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-81",
          "name": "Chicken Popcorn",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": false,
          "price": 175,
          "description": "Bite-sized tender chicken nuggets coated in crunchy seasoned breadcrumbs with garlic dip.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-popcorn.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-82",
          "name": "French Fries Chilli",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 135,
          "description": "Golden fries tossed in sweet and spicy Indo-Chinese chilli garlic sauce with capsicum.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/french-fries-chilli.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-83",
          "name": "Honey Potato Chilli",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 150,
          "description": "Crispy potato fingers glazed in a sticky honey-chilli sauce with toasted sesame seeds.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/honey-potato-chilli.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-84",
          "name": "Baby Corn Chilli",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 240,
          "description": "Crisp golden baby corn batons wok-tossed in spicy chilli soya glaze with spring onions.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/baby-corn-chilli.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-85",
          "name": "Mushroom Crispy chilli",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 240,
          "description": "Batter-crisped button mushrooms tossed with diced bell peppers, onions, and hot chilli sauce.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/mushroom-crispy-chilli.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-86",
          "name": "Corn Salt & Pepper",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 225,
          "description": "Crispy fried sweet corn tossed with freshly cracked black pepper, garlic, and scallions.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/corn-salt-pepper.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-87",
          "name": "Mushroom Salt & Pepper",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 235,
          "description": "Crunchy button mushrooms tossed with sea salt, crushed Malabar black pepper, and garlic.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/mushroom-salt-pepper.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-88",
          "name": "Paneer Salt & Pepper",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 235,
          "description": "Golden paneer cubes seasoned with cracked black pepper, garlic butter, and scallions.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-salt-pepper.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-89",
          "name": "Chicken 65",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": false,
          "price": 240,
          "description": "Famous South-Indian style boneless chicken tossed with fiery red chillies, curry leaves, and mustard.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-65.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-90",
          "name": "Chicken Lollipop",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": false,
          "price": 255,
          "description": "Crisp-fried chicken wings shaped into lollipops, tossed in zesty Schezwan garlic sauce.",
          "spicyLevel": 1,
          "isChefSpecial": true,
          "image": "/data/dishes/chicken-lollipop.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-91",
          "name": "Baby Corn Paprika",
          "category": "Starters & Snacks",
          "subCategory": "Starters",
          "isVeg": true,
          "price": 265,
          "description": "Crunchy baby corn tossed with smoky Spanish paprika, garlic butter, and fresh herbs.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/baby-corn-paprika.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-92",
          "name": "Veg Fried Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": true,
          "price": 95,
          "description": "Crispy golden fried dumplings packed with finely minced cabbage, carrots, spring onions, and ginger.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-fried-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-93",
          "name": "Veg Roasted Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": true,
          "price": 110,
          "description": "Tandoor-charred vegetable momos roasted with smokey spices and chaat masala, served with mint dip.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-roasted-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-94",
          "name": "Veg Crispy Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": true,
          "price": 115,
          "description": "Panko crumb-coated vegetable momos fried to extra crunchy perfection, served with garlic schezwan dip.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-crispy-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-95",
          "name": "Veg Afghani Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": true,
          "price": 130,
          "description": "Steamed vegetable momos drenched in a rich, creamy Afghani cashew-malai sauce with black pepper.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-afghani-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-96",
          "name": "Veg Crispy Afghani Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": true,
          "price": 150,
          "description": "Extra crunchy crumb-fried veg momos tossed in velvety Afghani malai gravy with roasted sesame.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-crispy-afghani-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-97",
          "name": "Paneer Fried Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": true,
          "price": 100,
          "description": "Crispy golden dumplings loaded with fresh spiced paneer, onions, and herbs, served with zesty chutney.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-fried-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-98",
          "name": "Paneer Roasted Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": true,
          "price": 115,
          "description": "Tandoori roasted paneer dumplings with a smoky charred exterior and soft paneer filling inside.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-roasted-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-99",
          "name": "Paneer Crispy Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": true,
          "price": 125,
          "description": "Crunchy crumb-coated paneer momos fried to golden perfection with sweet and spicy dips.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-crispy-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-100",
          "name": "Paneer Afghani Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": true,
          "price": 145,
          "description": "Soft paneer momos coated in luxurious Afghani malai cream, cashew paste, and fresh herbs.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-afghani-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-101",
          "name": "Paneer Crispy Afghani Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": true,
          "price": 160,
          "description": "Crispy paneer momos smothered in rich cardamom-infused cream and roasted aromatics.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-crispy-afghani-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-102",
          "name": "Chicken Fried Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": false,
          "price": 100,
          "description": "Deep-fried crisp flour pockets stuffed with juicy minced chicken, garlic, and coriander.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-fried-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-103",
          "name": "Chicken Roasted Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": false,
          "price": 115,
          "description": "Tandoor-blistered juicy chicken momos with a smoky coal aroma and chatpata seasoning.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-roasted-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-104",
          "name": "Chicken Crispy Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": false,
          "price": 125,
          "description": "Golden panko-crusted chicken momos with a crunchy bite and piping-hot juicy chicken center.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-crispy-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-105",
          "name": "Chicken Afghani Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": false,
          "price": 145,
          "description": "Juicy chicken dumplings tossed in rich, velvety Afghani cashew-cream gravy with fragrant spices.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-afghani-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-106",
          "name": "Chicken Crispy Afghani Momo",
          "category": "Momos & Fast Food",
          "subCategory": "Momos",
          "isVeg": false,
          "price": 160,
          "description": "Crunchy crumb-fried chicken momos bathed in luscious Afghani malai sauce.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-crispy-afghani-momo.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-107",
          "name": "Veg Cheese Burger",
          "category": "Momos & Fast Food",
          "subCategory": "Burger",
          "isVeg": true,
          "price": 100,
          "description": "Crisp golden spiced vegetable patty topped with melted cheddar cheese, sliced onions, and lettuce.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-cheese-burger.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-108",
          "name": "Egg Cheese Burger",
          "category": "Momos & Fast Food",
          "subCategory": "Burger",
          "isVeg": false,
          "price": 110,
          "description": "Double layered spiced egg omelette patty with melted cheese, caramelized onions, and garlic mayo.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/egg-cheese-burger.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-109",
          "name": "Paneer Cheese Burger",
          "category": "Momos & Fast Food",
          "subCategory": "Burger",
          "isVeg": true,
          "price": 115,
          "description": "Thick slab of seasoned crumb-fried paneer with melted mozzarella, fresh tomatoes, and tandoori mayo.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-cheese-burger.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-110",
          "name": "Chicken Cheese Burger",
          "category": "Momos & Fast Food",
          "subCategory": "Burger",
          "isVeg": false,
          "price": 125,
          "description": "Crisp golden chicken patty topped with molten cheddar slice, jalapeños, and special burger relish.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-cheese-burger.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-111",
          "name": "Veg Grilled Sandwich",
          "category": "Momos & Fast Food",
          "subCategory": "Sandwich",
          "isVeg": true,
          "price": 95,
          "description": "Triple-layer grilled bread filled with sliced cucumbers, tomatoes, capsicum, and mint chutney.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-grilled-sandwich.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-112",
          "name": "Egg Grilled Sandwich",
          "category": "Momos & Fast Food",
          "subCategory": "Sandwich",
          "isVeg": false,
          "price": 105,
          "description": "Fluffy masala egg scramble with black pepper, melted cheese, and sliced onions in golden toast.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/egg-grilled-sandwich.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-113",
          "name": "Cheese corn Grilled Sandwich",
          "category": "Momos & Fast Food",
          "subCategory": "Sandwich",
          "isVeg": true,
          "price": 120,
          "description": "Sweet golden corn kernels tossed with molten cheddar and mozzarella, oregano, and chili flakes.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/cheese-corn-grilled-sandwich.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-114",
          "name": "Paneer Grilled Sandwich",
          "category": "Momos & Fast Food",
          "subCategory": "Sandwich",
          "isVeg": true,
          "price": 125,
          "description": "Marinated cottage cheese cubes tossed in tandoori spices and capsicum, grilled with molten cheese.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-grilled-sandwich.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-115",
          "name": "Chicken Grilled Sandwich",
          "category": "Momos & Fast Food",
          "subCategory": "Sandwich",
          "isVeg": false,
          "price": 135,
          "description": "Shredded smoked chicken tossed in creamy pepper mayo, bell peppers, and melted cheese.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-grilled-sandwich.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-116",
          "name": "Veg Manchurian",
          "category": "Curries & Chinese",
          "subCategory": "Chinese",
          "isVeg": true,
          "price": 160,
          "description": "Golden vegetable dumplings simmered in a savory, tangy dark soy and ginger-garlic sauce.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-manchurian.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-117",
          "name": "Paneer Chilli",
          "category": "Curries & Chinese",
          "subCategory": "Chinese",
          "isVeg": true,
          "price": 185,
          "description": "Soft paneer cubes wok-tossed with fiery green chillies, bell peppers, onions, and dark soya glaze.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-chilli.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-118",
          "name": "Mushroom Chilli",
          "category": "Curries & Chinese",
          "subCategory": "Chinese",
          "isVeg": true,
          "price": 195,
          "description": "Button mushrooms wok-fried in spicy Indo-Chinese chilli garlic sauce with crunchy capsicum.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/mushroom-chilli.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-119",
          "name": "Chicken Bone Chilli",
          "category": "Curries & Chinese",
          "subCategory": "Chinese",
          "isVeg": false,
          "price": 200,
          "description": "Traditional bone-in chicken chunks tossed in spicy soy-chilli gravy with green onions.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-bone-chilli.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-120",
          "name": "Chicken Boneless Chilli",
          "category": "Curries & Chinese",
          "subCategory": "Chinese",
          "isVeg": false,
          "price": 225,
          "description": "Juicy boneless chicken cubes wok-tossed with red and green chillies, garlic, and soy sauce.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-boneless-chilli.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-121",
          "name": "Chicken Manchurian",
          "category": "Curries & Chinese",
          "subCategory": "Chinese",
          "isVeg": false,
          "price": 235,
          "description": "Tender chicken meatballs glazed in a glossy, tangy ginger-coriander Manchurian sauce.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-manchurian.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-122",
          "name": "Chicken Schezwan",
          "category": "Curries & Chinese",
          "subCategory": "Chinese",
          "isVeg": false,
          "price": 240,
          "description": "Spicy chicken morsels cooked in authentic fiery Sichuan pepper and roasted chilli paste.",
          "spicyLevel": 2,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-schezwan.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-123",
          "name": "Onion Salad",
          "category": "Beverages & Soups",
          "subCategory": "Salad",
          "isVeg": true,
          "price": 40,
          "description": "Freshly sliced crisp red onion rings seasoned with chaat masala, lemon wedges, and green chillies.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/onion-salad.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-124",
          "name": "Green Salad",
          "category": "Beverages & Soups",
          "subCategory": "Salad",
          "isVeg": true,
          "price": 55,
          "description": "Fresh farm salad platter of sliced cucumbers, tomatoes, carrots, onions, and lemon wedges.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/green-salad.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-125",
          "name": "Mix Raita",
          "category": "Beverages & Soups",
          "subCategory": "Raita",
          "isVeg": true,
          "price": 40,
          "description": "Chilled creamy yogurt whipped with finely diced cucumbers, onions, tomatoes, and roasted cumin.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/mix-raita.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-126",
          "name": "Boondi Raita",
          "category": "Beverages & Soups",
          "subCategory": "Raita",
          "isVeg": true,
          "price": 35,
          "description": "Classic spiced yogurt mixed with crunchy gram flour boondi pearls and fragrant mint powder.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/boondi-raita.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-127",
          "name": "Veg Roll",
          "category": "Momos & Fast Food",
          "subCategory": "Rolls",
          "isVeg": true,
          "price": 55,
          "description": "Flaky paratha rolled with seasoned sautéed vegetables, crunchy sliced onions, and tangy mint chutney.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-roll.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-128",
          "name": "Egg Roll",
          "category": "Momos & Fast Food",
          "subCategory": "Rolls",
          "isVeg": false,
          "price": 65,
          "description": "Golden paratha coated with a fried egg and rolled with spiced onions, lemon juice, and sauces.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/egg-roll.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-129",
          "name": "Cheese corn Roll",
          "category": "Momos & Fast Food",
          "subCategory": "Rolls",
          "isVeg": true,
          "price": 80,
          "description": "Crispy paratha wrap stuffed with sweet corn, molten mozzarella cheese, and chatpata seasoning.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/cheese-corn-roll.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-130",
          "name": "Paneer Roll",
          "category": "Momos & Fast Food",
          "subCategory": "Rolls",
          "isVeg": true,
          "price": 95,
          "description": "Warm paratha wrap filled with tandoori spiced paneer tikka, crunchy onions, and green chutney.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-roll.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-131",
          "name": "Chicken Roll",
          "category": "Momos & Fast Food",
          "subCategory": "Rolls",
          "isVeg": false,
          "price": 105,
          "description": "Flaky crisp paratha rolled with juicy spiced chicken boti, sliced onions, and lemon pepper.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-roll.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-132",
          "name": "Chicken Egg Roll",
          "category": "Momos & Fast Food",
          "subCategory": "Rolls",
          "isVeg": false,
          "price": 125,
          "description": "Double delight of fluffy egg-coated paratha stuffed with tender spiced chicken chunks.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-egg-roll.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-133",
          "name": "Sweet Corn Soup",
          "category": "Beverages & Soups",
          "subCategory": "Soup",
          "isVeg": true,
          "price": 85,
          "description": "Comforting creamy sweet corn soup with tender corn kernels and gentle seasonings.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/sweet-corn-soup.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-134",
          "name": "Veg Hot & Sour Soup",
          "category": "Beverages & Soups",
          "subCategory": "Soup",
          "isVeg": true,
          "price": 85,
          "description": "Spicy and tangy Chinese broth loaded with shredded vegetables, mushrooms, and black pepper.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-hot-sour-soup.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-135",
          "name": "Veg Manchow Soup",
          "category": "Beverages & Soups",
          "subCategory": "Soup",
          "isVeg": true,
          "price": 110,
          "description": "Dark, savory vegetable soup flavored with garlic, coriander, and served with crispy fried noodles.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/veg-manchow-soup.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-136",
          "name": "Tomato Soup",
          "category": "Beverages & Soups",
          "subCategory": "Soup",
          "isVeg": true,
          "price": 85,
          "description": "Rich velvety ripe tomato soup simmered with fresh herbs, butter, and served with crunchy croutons.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/tomato-soup.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-137",
          "name": "Chicken Corn Soup",
          "category": "Beverages & Soups",
          "subCategory": "Soup",
          "isVeg": false,
          "price": 95,
          "description": "Delicate, soothing broth with tender shredded chicken, sweet corn, and egg drops.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-corn-soup.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-138",
          "name": "Chicken Hot & Sour Soup",
          "category": "Beverages & Soups",
          "subCategory": "Soup",
          "isVeg": false,
          "price": 125,
          "description": "Fiery and sour chicken broth packed with shredded chicken, bamboo shoots, and green chillies.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-hot-sour-soup.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-139",
          "name": "Chicken Manchow Soup",
          "category": "Beverages & Soups",
          "subCategory": "Soup",
          "isVeg": false,
          "price": 135,
          "description": "Bold, aromatic chicken soup with ginger, garlic, and fresh herbs, topped with fried noodles.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-manchow-soup.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-140",
          "name": "Paneer Tikka",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Veg)",
          "isVeg": true,
          "price": 225,
          "description": "Fresh cottage cheese cubes marinated in spiced hung curd, skewered and charred over live embers.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-tikka.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-141",
          "name": "Paneer Seekh Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Veg)",
          "isVeg": true,
          "price": 235,
          "description": "Minced spiced paneer blended with herbs and royal Lucknowi seasonings, grilled on skewers.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-seekh-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-142",
          "name": "Paneer Achari Tikka",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Veg)",
          "isVeg": true,
          "price": 235,
          "description": "Paneer cubes infused with punchy pickle spices, mustard oil, and charred in the tandoor.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-achari-tikka.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-143",
          "name": "Paneer Malai Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Veg)",
          "isVeg": true,
          "price": 340,
          "description": "Melt-in-mouth paneer cubes soaked in rich cashew cream, cardamom, and roasted gentle over coal.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/paneer-malai-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-144",
          "name": "Harabhara Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Veg)",
          "isVeg": true,
          "price": 320,
          "description": "Pan-grilled spinach and green pea patties seasoned with ginger, cumin, and roasted cashews.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/harabhara-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-145",
          "name": "Tandoori Chicken Half",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 240,
          "description": "Two chicken quarters steeped in Kashmiri deghi mirch and mustard oil, roasted in clay oven.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/tandoori-chicken-half.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-146",
          "name": "Chicken Patiala Half",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 240,
          "description": "Tender chicken marinated in Punjabi spices, slow-grilled and topped with rich Mughlai glaze.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-patiala-half.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-147",
          "name": "Chicken Tikka",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 250,
          "description": "Boneless chicken cubes steeped in ginger, garlic, and curd marinade, roasted crisp in the tandoor.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-tikka.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-148",
          "name": "Chicken Seekh Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 250,
          "description": "Minced chicken blended with fresh herbs and Lucknowi aromatics, skewered and charcoal-grilled.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-seekh-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-149",
          "name": "Chicken Boti Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 261,
          "description": "Tender boneless chicken boti bites steeped in spicy marinade, charred over glowing coal embers.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-boti-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-150",
          "name": "Chicken Hariyali Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 263,
          "description": "Succulent chicken morsels infused with fresh garden mint, coriander, and green chillies.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-hariyali-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-151",
          "name": "Chicken Kali Mirch Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 265,
          "description": "Creamy tandoori chicken marinated in freshly crushed Malabar black pepper and fresh cream.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-kali-mirch-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-152",
          "name": "Chicken Reshmi Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 267,
          "description": "Silken-smooth chicken kebabs tenderized with egg whites, clotted cream, and subtle saffron.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-reshmi-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-153",
          "name": "Chicken Achari Tikka",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 290,
          "description": "Bold and tangy chicken tikka steeped in panch-phoran pickle spices and mustard oil.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-achari-tikka.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-154",
          "name": "Chicken Garlic Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 325,
          "description": "Charcoal-roasted chicken skewers steeped in roasted golden garlic butter and crushed herbs.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-garlic-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-155",
          "name": "Chicken Malai Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 365,
          "description": "Decadent chicken cubes bathed in rich cardamom cream, cashew nut paste, and melted cheese.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-malai-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-156",
          "name": "Tangdi Kebab (4Leg pcs.)",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 327,
          "description": "Four whole chicken drumsticks marinated in royal spices and slow-roasted in the clay oven.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/tangdi-kebab-4leg-pcs.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-157",
          "name": "Chicken Cheese Kebab",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 400,
          "description": "Succulent chicken kebabs stuffed with molten mozzarella and mild green herbs.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-cheese-kebab.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-158",
          "name": "Tandoori Chicken Full",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 410,
          "description": "Whole chicken steeped in traditional tandoori marinade, slow-roasted over coal embers.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/tandoori-chicken-full.jpg",
          "serves": "1-2 Persons"
      },
      {
          "id": "m-159",
          "name": "Chicken Patiala Full",
          "category": "Tandoori & Kebabs",
          "subCategory": "Tandoori (Chicken)",
          "isVeg": false,
          "price": 409,
          "description": "Whole tandoori chicken cooked in royal Patiala style with roasted aromatics and rich glaze.",
          "spicyLevel": 1,
          "isChefSpecial": false,
          "image": "/data/dishes/chicken-patiala-full.jpg",
          "serves": "1-2 Persons"
      }
  ] as MenuItem[],

  seatingOptions: [
    {
      id: "maharaja",
      name: "Maharaja Family Chamber",
      description: "Exclusive air-conditioned dining area with comfortable velvet seating for family gatherings up to 12 guests.",
      badge: "Family & Groups"
    },
    {
      id: "courtyard",
      name: "Main Royal Hall",
      description: "Dine under warm chandeliers with gentle background music and attentive table service.",
      badge: "Most Popular"
    },
    {
      id: "terrace",
      name: "Cozy Couple Corner",
      description: "Private booth seating perfect for intimate dinners, dates, and celebrations.",
      badge: "Couples & Dates"
    }
  ]
};
